/**
 * Lead Seed Data
 * Sample leads at various stages of the qualification pipeline
 */

export const LeadSeedData = [
  { first_name: 'Alex', last_name: 'Rivera', email: 'alex.rivera@initech.example.com', company: 'Initech Systems', title: 'IT Director', status: 'new', lead_source: 'web', industry: 'technology', annual_revenue: 4000000, phone: '+1-408-555-1001', city: 'San Jose', state: 'CA', country: 'US', lead_score: 25 },
  { first_name: 'Priya', last_name: 'Sharma', email: 'priya.sharma@vortexlabs.example.com', company: 'Vortex Labs', title: 'VP of Product', status: 'contacted', lead_source: 'referral', industry: 'technology', annual_revenue: 9000000, phone: '+1-650-555-1002', city: 'Palo Alto', state: 'CA', country: 'US', lead_score: 55 },
  { first_name: 'Marcus', last_name: 'Green', email: 'marcus.green@pinnacleins.example.com', company: 'Pinnacle Insurance', title: 'Chief Information Officer', status: 'working', lead_source: 'trade_show', industry: 'financial_services', annual_revenue: 30000000, phone: '+1-860-555-1003', city: 'Hartford', state: 'CT', country: 'US', lead_score: 72 },
  { first_name: 'Yuki', last_name: 'Tanaka', email: 'yuki.tanaka@zenithpharma.example.com', company: 'Zenith Pharma', title: 'Head of Operations', status: 'qualified', lead_source: 'partner', industry: 'healthcare', annual_revenue: 18000000, phone: '+1-609-555-1004', city: 'Princeton', state: 'NJ', country: 'US', lead_score: 88 },
  { first_name: 'Carlos', last_name: 'Mendez', email: 'carlos.mendez@terrabuilders.example.com', company: 'Terra Builders', title: 'Project Manager', status: 'new', lead_source: 'cold_call', industry: 'construction', annual_revenue: 6000000, phone: '+1-303-555-1005', city: 'Denver', state: 'CO', country: 'US', lead_score: 15 },
  { first_name: 'Rebecca', last_name: 'Stone', email: 'rebecca.stone@luminaedu.example.com', company: 'Lumina Education', title: 'Dean of Technology', status: 'contacted', lead_source: 'web', industry: 'education', annual_revenue: 2500000, phone: '+1-919-555-1006', city: 'Raleigh', state: 'NC', country: 'US', lead_score: 40 },
  { first_name: 'Jordan', last_name: 'Blake', email: 'jordan.blake@swiftlogistics.example.com', company: 'Swift Logistics', title: 'Operations Manager', status: 'working', lead_source: 'referral', industry: 'transportation', annual_revenue: 22000000, phone: '+1-901-555-1007', city: 'Memphis', state: 'TN', country: 'US', lead_score: 62 },
  { first_name: 'Samantha', last_name: 'Hayes', email: 'samantha.hayes@verdantagri.example.com', company: 'Verdant Agriculture', title: 'Procurement Director', status: 'qualified', lead_source: 'trade_show', industry: 'agriculture', annual_revenue: 11000000, phone: '+1-515-555-1008', city: 'Des Moines', state: 'IA', country: 'US', lead_score: 81 },
  { first_name: 'Derek', last_name: 'Olson', email: 'derek.olson@northstarretail.example.com', company: 'NorthStar Retail', title: 'VP of Sales', status: 'unqualified', lead_source: 'cold_call', industry: 'retail', annual_revenue: 1500000, phone: '+1-612-555-1009', city: 'Minneapolis', state: 'MN', country: 'US', lead_score: 10 },
  { first_name: 'Fatima', last_name: 'Al-Hassan', email: 'fatima.alhassan@crescentfin.example.com', company: 'Crescent Financial', title: 'Senior Analyst', status: 'new', lead_source: 'web', industry: 'financial_services', annual_revenue: 7000000, phone: '+1-704-555-1010', city: 'Charlotte', state: 'NC', country: 'US', lead_score: 30 },
  { first_name: 'Patrick', last_name: 'O\'Reilly', email: 'patrick.oreilly@celticmedia.example.com', company: 'Celtic Media Group', title: 'Managing Editor', status: 'contacted', lead_source: 'partner', industry: 'media_entertainment', annual_revenue: 5000000, phone: '+1-617-555-1011', city: 'Boston', state: 'MA', country: 'US', lead_score: 45 },
  { first_name: 'Lena', last_name: 'Kowalski', email: 'lena.kowalski@apexmfg.example.com', company: 'Apex Manufacturing', title: 'Plant Manager', status: 'working', lead_source: 'trade_show', industry: 'manufacturing', annual_revenue: 35000000, phone: '+1-414-555-1012', city: 'Milwaukee', state: 'WI', country: 'US', lead_score: 68 },
  { first_name: 'Victor', last_name: 'Reyes', email: 'victor.reyes@solarwaveenergy.example.com', company: 'SolarWave Energy', title: 'Business Development Manager', status: 'qualified', lead_source: 'referral', industry: 'energy', annual_revenue: 14000000, phone: '+1-602-555-1013', city: 'Phoenix', state: 'AZ', country: 'US', lead_score: 85 },
  { first_name: 'Nina', last_name: 'Petrova', email: 'nina.petrova@quantumdata.example.com', company: 'Quantum Data Solutions', title: 'Data Science Lead', status: 'new', lead_source: 'web', industry: 'technology', annual_revenue: 3500000, phone: '+1-503-555-1014', city: 'Portland', state: 'OR', country: 'US', lead_score: 20 },
  { first_name: 'Trevor', last_name: 'Banks', email: 'trevor.banks@harborclinics.example.com', company: 'Harbor Health Clinics', title: 'Administrator', status: 'contacted', lead_source: 'cold_call', industry: 'healthcare', annual_revenue: 6500000, phone: '+1-619-555-1015', city: 'San Diego', state: 'CA', country: 'US', lead_score: 38 },
  { first_name: 'Isabelle', last_name: 'Dupont', email: 'isabelle.dupont@eliteproperties.example.com', company: 'Elite Properties', title: 'Acquisitions Manager', status: 'working', lead_source: 'partner', industry: 'realestate', annual_revenue: 28000000, phone: '+1-702-555-1016', city: 'Las Vegas', state: 'NV', country: 'US', lead_score: 70 },
  { first_name: 'Ryan', last_name: 'Foster', email: 'ryan.foster@skylineaero.example.com', company: 'Skyline Aerospace', title: 'Engineering Director', status: 'qualified', lead_source: 'trade_show', industry: 'aerospace', annual_revenue: 50000000, phone: '+1-316-555-1017', city: 'Wichita', state: 'KS', country: 'US', lead_score: 92 },
  { first_name: 'Monica', last_name: 'Chang', email: 'monica.chang@pearlfoods.example.com', company: 'Pearl Foods International', title: 'Supply Chain VP', status: 'unqualified', lead_source: 'web', industry: 'food_beverage', annual_revenue: 2000000, phone: '+1-404-555-1018', city: 'Atlanta', state: 'GA', country: 'US', lead_score: 8 },
  { first_name: 'Elliott', last_name: 'Grant', email: 'elliott.grant@urbandev.example.com', company: 'Urban Development Corp', title: 'CFO', status: 'new', lead_source: 'referral', industry: 'realestate', annual_revenue: 16000000, phone: '+1-215-555-1019', city: 'Philadelphia', state: 'PA', country: 'US', lead_score: 35 },
  { first_name: 'Hannah', last_name: 'Sullivan', email: 'hannah.sullivan@brightwelltech.example.com', company: 'Brightwell Technologies', title: 'Product Manager', status: 'contacted', lead_source: 'partner', industry: 'technology', annual_revenue: 8500000, phone: '+1-512-555-1020', city: 'Austin', state: 'TX', country: 'US', lead_score: 50 }
];

export default LeadSeedData;
