# Pricebook Object Definition
# 价格表管理 - Sales Force Automation Domain
# Follows @objectstack/spec standard for enterprise CRM

name: Pricebook
label: 价格表
labelPlural: 价格表
icon: tag
description: 多币种、多地区、多渠道的价格管理

# Enable core features
features:
  searchable: true
  trackFieldHistory: true
  enableNotes: true
  enableAttachments: false

# Field Definitions
fields:
  # Basic Information
  - name: Name
    type: text
    label: 价格表名称
    required: true
    searchable: true
    length: 255
    
  - name: Description
    type: textarea
    label: 描述
    length: 1000
    
  - name: IsActive
    type: checkbox
    label: 启用
    defaultValue: true
    
  - name: IsStandard
    type: checkbox
    label: 标准价格表
    defaultValue: false
    readonly: true
    description: 系统只能有一个标准价格表
    
  # Pricing Strategy
  - name: PricingStrategy
    type: select
    label: 定价策略
    options:
      - label: 标准定价
        value: Standard
      - label: 折扣定价
        value: Discount
      - label: 渠道定价
        value: Channel
      - label: 地区定价
        value: Regional
      - label: VIP 定价
        value: VIP
      - label: 促销定价
        value: Promotion
      - label: 批量定价
        value: Volume
        
  # Geographic & Currency
  - name: Currency
    type: select
    label: 币种
    required: true
    defaultValue: CNY
    options:
      - label: 人民币 (CNY)
        value: CNY
      - label: 美元 (USD)
        value: USD
      - label: 欧元 (EUR)
        value: EUR
      - label: 英镑 (GBP)
        value: GBP
      - label: 日元 (JPY)
        value: JPY
      - label: 港币 (HKD)
        value: HKD
      - label: 新加坡元 (SGD)
        value: SGD
        
  - name: Region
    type: select
    label: 适用地区
    options:
      - label: 全球
        value: Global
      - label: 中国大陆
        value: China Mainland
      - label: 港澳台
        value: HK/Macau/Taiwan
      - label: 北美
        value: North America
      - label: 欧洲
        value: Europe
      - label: 亚太
        value: Asia Pacific
      - label: 中东
        value: Middle East
      - label: 其他
        value: Other
        
  # Channel
  - name: SalesChannel
    type: select
    label: 销售渠道
    options:
      - label: 直销
        value: Direct
      - label: 渠道
        value: Channel
      - label: 在线
        value: Online
      - label: 零售
        value: Retail
      - label: 分销
        value: Distribution
      - label: 代理
        value: Agent
        
  # Validity Period
  - name: StartDate
    type: date
    label: 生效日期
    
  - name: EndDate
    type: date
    label: 失效日期
    
  - name: IsValid
    type: checkbox
    label: 当前有效
    readonly: true
    description: 根据日期范围自动计算
    
  # Statistics
  - name: TotalProducts
    type: number
    label: 产品总数
    precision: 0
    readonly: true
    description: 价格表中的产品数量
    
  - name: AverageDiscount
    type: percent
    label: 平均折扣
    readonly: true
    description: 相对于标准价格表的平均折扣率

# Relationships
relationships:
  - name: PricebookEntries
    type: hasMany
    object: PricebookEntry
    foreignKey: PricebookId
    label: 价格表条目
    
  - name: Opportunities
    type: hasMany
    object: Opportunity
    foreignKey: PricebookId
    label: 关联商机
    
  - name: Quotes
    type: hasMany
    object: Quote
    foreignKey: PricebookId
    label: 关联报价单

# List Views
listViews:
  - name: AllPricebooks
    label: 所有价格表
    filters: []
    columns:
      - Name
      - Currency
      - PricingStrategy
      - Region
      - SalesChannel
      - IsActive
      - IsStandard
      - TotalProducts
    sortBy: Name
    sortOrder: asc
    
  - name: ActivePricebooks
    label: 启用的价格表
    filters:
      - field: IsActive
        operator: equals
        value: true
    columns:
      - Name
      - Currency
      - PricingStrategy
      - StartDate
      - EndDate
      - TotalProducts
    sortBy: Name
    sortOrder: asc
    
  - name: ValidPricebooks
    label: 当前有效
    filters:
      - field: IsValid
        operator: equals
        value: true
      - field: IsActive
        operator: equals
        value: true
    columns:
      - Name
      - Currency
      - Region
      - SalesChannel
      - TotalProducts
    sortBy: Name
    sortOrder: asc
    
  - name: ByCurrency
    label: 按币种
    filters:
      - field: IsActive
        operator: equals
        value: true
    columns:
      - Name
      - Currency
      - Region
      - PricingStrategy
      - TotalProducts
    sortBy: Currency
    sortOrder: asc
    
  - name: ExpiringPricebooks
    label: 即将到期
    filters:
      - field: EndDate
        operator: next_n_days
        value: 30
      - field: IsActive
        operator: equals
        value: true
    columns:
      - Name
      - Currency
      - EndDate
      - TotalProducts
    sortBy: EndDate
    sortOrder: asc

# Page Layout
pageLayout:
  sections:
    - label: 价格表信息
      columns: 2
      fields:
        - Name
        - IsActive
        - IsStandard
        - PricingStrategy
        
    - label: 地区与币种
      columns: 2
      fields:
        - Currency
        - Region
        - SalesChannel
        
    - label: 有效期
      columns: 2
      fields:
        - StartDate
        - EndDate
        - IsValid
        
    - label: 统计信息
      columns: 2
      fields:
        - TotalProducts
        - AverageDiscount
        
    - label: 描述
      columns: 1
      fields:
        - Description

# Validation Rules
validationRules:
  - name: EndDateAfterStartDate
    errorMessage: 失效日期必须晚于生效日期
    formula: |
      AND(
        NOT(ISBLANK(StartDate)),
        NOT(ISBLANK(EndDate)),
        EndDate < StartDate
      )
      
  - name: OnlyOneStandardPricebook
    errorMessage: 系统只能有一个标准价格表
    formula: |
      AND(
        IsStandard = true,
        $ExistingStandardPricebook.Count > 0
      )
      
  - name: StandardPricebookMustUseCNY
    errorMessage: 标准价格表必须使用人民币 (CNY)
    formula: |
      AND(
        IsStandard = true,
        Currency != "CNY"
      )

# Triggers
triggers:
  - name: ValidityCalculation
    event: beforeInsert, beforeUpdate
    description: 根据日期范围计算是否有效
    
  - name: ProductCountAggregation
    event: afterUpdate
    description: 统计价格表中的产品数量
