/**
 * Dashboard AI Enhancement Actions
 *
 * AI-powered dashboard capabilities:
 * 1. Auto-Generate Dashboard - create layout based on user role
 * 2. KPI Anomaly Detection - identify anomalies in KPI values
 * 3. Widget Recommendations - suggest widgets based on user activity
 */

import { broker } from '../db.js';

// ============================================================================
// 1. AUTO-GENERATE DASHBOARD
// ============================================================================

export interface AutoGenerateDashboardRequest {
  /** User role (e.g., "sales_manager", "cfo", "support_lead") */
  userRole: string;
  /** Optional: specific objects to focus on */
  focusObjects?: string[];
}

export interface AutoGenerateDashboardResponse {
  /** Created dashboard ID */
  dashboardId: string;
  /** Dashboard definition */
  dashboard: {
    name: string;
    widgets: Array<{
      type: string;
      title: string;
      report_id?: string;
      kpi_name?: string;
      position: { col: number; row: number; width: number; height: number };
    }>;
    layout_config: { columns: number; rows: number };
  };
  /** Explanation of widget selection */
  explanation: string;
}

/**
 * Auto-generate a dashboard layout based on user role
 */
export async function autoGenerateDashboard(request: AutoGenerateDashboardRequest): Promise<AutoGenerateDashboardResponse> {
  const { userRole, focusObjects } = request;

  if (!userRole) {
    throw new Error('userRole is required');
  }

  // Fetch existing KPIs to populate widgets
  const kpis = await broker.find('kpi', { limit: 10 });

  // Fetch top reports for widget candidates
  const reports = await broker.find('report', {
    sort: { run_count: -1 },
    limit: 10
  });

  const systemPrompt = `
You are a dashboard design AI.

# User Role: ${userRole}
${focusObjects ? `# Focus Objects: ${focusObjects.join(', ')}` : ''}

# Available KPIs
${kpis.map(k => `- ${k.name} (${k.metric_type})`).join('\n') || 'None'}

# Popular Reports
${reports.map(r => `- ${r.name} (${r.report_type}, runs: ${r.run_count})`).join('\n') || 'None'}

# Task
Generate a dashboard layout with the most relevant widgets for this role.

# Output Format
{
  "dashboard": {
    "name": "Sales Manager Dashboard",
    "widgets": [
      {"type": "kpi", "title": "Revenue MTD", "kpi_name": "revenue_mtd", "position": {"col": 0, "row": 0, "width": 3, "height": 2}},
      {"type": "chart", "title": "Pipeline by Stage", "report_id": "rpt_001", "position": {"col": 3, "row": 0, "width": 6, "height": 4}}
    ],
    "layout_config": {"columns": 12, "rows": 8}
  },
  "explanation": "Designed for sales manager with KPI overview and pipeline visibility."
}
`.trim();

  const llmResponse = await callLLM(systemPrompt);
  const parsed = JSON.parse(llmResponse);

  // Persist the dashboard
  const created = await broker.insert('analytics_dashboard', {
    name: parsed.dashboard.name,
    widgets: JSON.stringify(parsed.dashboard.widgets),
    layout_config: JSON.stringify(parsed.dashboard.layout_config),
    is_default: false
  });

  return {
    dashboardId: created._id,
    dashboard: parsed.dashboard,
    explanation: parsed.explanation
  };
}

// ============================================================================
// 2. KPI ANOMALY DETECTION
// ============================================================================

export interface DetectKPIAnomaliesRequest {
  /** Optional: specific KPI IDs to analyse. If omitted, analyses all KPIs. */
  kpiIds?: string[];
}

export interface KPIAnomaly {
  kpiId: string;
  kpiName: string;
  currentValue: number;
  expectedRange: { min: number; max: number };
  deviation: number;
  severity: 'low' | 'medium' | 'high' | 'critical';
  description: string;
}

export interface DetectKPIAnomaliesResponse {
  /** Detected anomalies */
  anomalies: KPIAnomaly[];
  /** Total KPIs analysed */
  analysedCount: number;
  /** Summary */
  summary: string;
}

/**
 * Identify anomalies in KPI values
 */
export async function detectKPIAnomalies(request: DetectKPIAnomaliesRequest): Promise<DetectKPIAnomaliesResponse> {
  let kpis: any[];

  if (request.kpiIds && request.kpiIds.length > 0) {
    const results = await Promise.all(
      request.kpiIds.map(id => broker.findOne('kpi', id))
    );
    kpis = results.filter(Boolean);
  } else {
    kpis = await broker.find('kpi', { limit: 50 });
  }

  if (kpis.length === 0) {
    return { anomalies: [], analysedCount: 0, summary: 'No KPIs found to analyse.' };
  }

  const systemPrompt = `
You are an anomaly detection AI for business KPIs.

# KPIs to Analyse
${kpis.map(k => `- ${k.name}: current=${k.current_value}, target=${k.target_value}, trend=${k.trend || 'unknown'}, warning=${k.threshold_warning ?? 'N/A'}, critical=${k.threshold_critical ?? 'N/A'}`).join('\n')}

# Task
Identify anomalous KPI values — those significantly deviating from expected ranges.

# Output Format
{
  "anomalies": [
    {
      "kpiId": "kpi_001",
      "kpiName": "Revenue MTD",
      "currentValue": 45000,
      "expectedRange": {"min": 80000, "max": 120000},
      "deviation": -43.75,
      "severity": "critical",
      "description": "Revenue is 44% below the expected minimum for this period"
    }
  ],
  "summary": "Found 1 critical anomaly out of 5 KPIs analysed."
}
`.trim();

  const llmResponse = await callLLM(systemPrompt);
  const parsed = JSON.parse(llmResponse);

  return {
    anomalies: parsed.anomalies,
    analysedCount: kpis.length,
    summary: parsed.summary
  };
}

// ============================================================================
// 3. WIDGET RECOMMENDATIONS
// ============================================================================

export interface RecommendWidgetsRequest {
  /** Dashboard ID to recommend widgets for */
  dashboardId: string;
  /** Maximum number of recommendations */
  maxRecommendations?: number;
}

export interface WidgetRecommendation {
  type: string;
  title: string;
  description: string;
  relevanceScore: number;
  config: Record<string, any>;
}

export interface RecommendWidgetsResponse {
  /** Recommended widgets */
  recommendations: WidgetRecommendation[];
  /** Reasoning */
  reasoning: string;
}

/**
 * Suggest widgets based on user activity and dashboard context
 */
export async function recommendWidgets(request: RecommendWidgetsRequest): Promise<RecommendWidgetsResponse> {
  const { dashboardId, maxRecommendations } = request;

  if (!dashboardId) {
    throw new Error('dashboardId is required');
  }

  const dashboard = await broker.findOne('analytics_dashboard', dashboardId);

  // Parse existing widgets to avoid duplicates
  let existingWidgets: any[] = [];
  if (dashboard.widgets) {
    try {
      existingWidgets = typeof dashboard.widgets === 'string'
        ? JSON.parse(dashboard.widgets)
        : dashboard.widgets;
    } catch {
      existingWidgets = [];
    }
  }

  // Fetch popular reports not yet on the dashboard
  const reports = await broker.find('report', {
    sort: { run_count: -1 },
    limit: 20
  });

  const kpis = await broker.find('kpi', { limit: 20 });

  const systemPrompt = `
You are a dashboard optimisation AI.

# Current Dashboard: ${dashboard.name}
# Existing Widgets (${existingWidgets.length}):
${existingWidgets.map((w: any) => `- ${w.type}: ${w.title}`).join('\n') || 'None'}

# Available Reports
${reports.map(r => `- ${r.name} (${r.report_type})`).join('\n') || 'None'}

# Available KPIs
${kpis.map(k => `- ${k.name} (${k.metric_type})`).join('\n') || 'None'}

# Task
Recommend up to ${maxRecommendations || 5} widgets that would add the most value to this dashboard.

# Output Format
{
  "recommendations": [
    {
      "type": "chart",
      "title": "Revenue Trend",
      "description": "Line chart showing revenue over time",
      "relevanceScore": 95,
      "config": {"chart_type": "line", "object_name": "opportunity"}
    }
  ],
  "reasoning": "Added revenue trend because the dashboard lacks time-series data."
}
`.trim();

  const llmResponse = await callLLM(systemPrompt);
  return JSON.parse(llmResponse);
}

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

async function callLLM(prompt: string): Promise<string> {
  console.log('🤖 Calling LLM API for dashboard AI...');
  await new Promise(resolve => setTimeout(resolve, 500));

  if (prompt.includes('dashboard layout')) {
    return JSON.stringify({
      dashboard: {
        name: 'Sales Manager Dashboard',
        widgets: [
          { type: 'kpi', title: 'Revenue MTD', kpi_name: 'revenue_mtd', position: { col: 0, row: 0, width: 3, height: 2 } },
          { type: 'kpi', title: 'Deals Won', kpi_name: 'deals_won', position: { col: 3, row: 0, width: 3, height: 2 } },
          { type: 'kpi', title: 'Win Rate', kpi_name: 'win_rate', position: { col: 6, row: 0, width: 3, height: 2 } },
          { type: 'kpi', title: 'Avg Deal Size', kpi_name: 'avg_deal', position: { col: 9, row: 0, width: 3, height: 2 } },
          { type: 'chart', title: 'Pipeline by Stage', position: { col: 0, row: 2, width: 6, height: 4 } },
          { type: 'chart', title: 'Revenue Trend', position: { col: 6, row: 2, width: 6, height: 4 } },
          { type: 'table', title: 'Top Opportunities', position: { col: 0, row: 6, width: 12, height: 4 } }
        ],
        layout_config: { columns: 12, rows: 10 }
      },
      explanation: 'Dashboard designed for sales managers with KPI cards at the top, pipeline and trend charts in the middle, and a deals table at the bottom.'
    });
  }

  if (prompt.includes('anomaly detection')) {
    return JSON.stringify({
      anomalies: [
        {
          kpiId: 'kpi_001',
          kpiName: 'Revenue MTD',
          currentValue: 45000,
          expectedRange: { min: 80000, max: 120000 },
          deviation: -43.75,
          severity: 'critical',
          description: 'Revenue is 44% below the expected minimum for this period'
        }
      ],
      summary: 'Found 1 critical anomaly across the analysed KPIs.'
    });
  }

  // Widget recommendations
  return JSON.stringify({
    recommendations: [
      { type: 'chart', title: 'Revenue Trend', description: 'Line chart showing revenue over time', relevanceScore: 95, config: { chart_type: 'line', object_name: 'opportunity' } },
      { type: 'kpi', title: 'Customer Satisfaction', description: 'CSAT score KPI card', relevanceScore: 88, config: { kpi_name: 'csat_score' } },
      { type: 'table', title: 'Recent Activities', description: 'Latest activities across accounts', relevanceScore: 82, config: { object_name: 'activity', limit: 10 } }
    ],
    reasoning: 'Added revenue trend for time-series visibility, CSAT for customer health, and recent activities for engagement context.'
  });
}

export default {
  autoGenerateDashboard,
  detectKPIAnomalies,
  recommendWidgets
};
