/**
 * Knowledge Base Article Seed Data
 * Sample articles covering onboarding, troubleshooting, and best practices
 */

export const KbArticleSeedData = [
  { title: 'Getting Started with HotCRM', summary: 'A beginner-friendly guide to setting up your HotCRM workspace and inviting your team.', body: '## Getting Started with HotCRM\n\nWelcome to HotCRM! Follow these steps to get up and running:\n\n1. **Create your workspace** — Sign in and name your organization.\n2. **Invite team members** — Go to Settings → Users and send invitations.\n3. **Import your data** — Use the Import Wizard to bring in contacts and accounts from CSV.\n4. **Customize your pipeline** — Navigate to Sales → Pipeline Settings to define your deal stages.\n\n> **Tip:** Enable the AI Copilot in Settings → AI to get intelligent suggestions from day one.', category: 'getting_started', status: 'published', is_featured: true, view_count: 4820, helpful_count: 387 },
  { title: 'Troubleshooting SSO Login Failures', summary: 'Common causes and fixes for SAML-based single sign-on authentication issues.', body: '## Troubleshooting SSO Login Failures\n\nIf users cannot log in via SSO, check the following:\n\n### 1. Certificate Expiration\nVerify that your Identity Provider certificate has not expired. Re-upload a valid certificate under Settings → Security → SSO.\n\n### 2. Assertion Consumer Service URL\nEnsure the ACS URL in your IdP matches:\n```\nhttps://app.hotcrm.io/auth/saml/callback\n```\n\n### 3. Clock Skew\nSAML assertions are time-sensitive. Ensure your IdP server clock is synchronized with NTP.\n\n### 4. Attribute Mapping\nConfirm that `email` and `name` attributes are mapped correctly in your IdP configuration.', category: 'troubleshooting', status: 'published', is_featured: false, view_count: 2150, helpful_count: 198 },
  { title: 'Best Practices for Pipeline Management', summary: 'Proven strategies to keep your sales pipeline healthy, accurate, and actionable.', body: '## Best Practices for Pipeline Management\n\n### Keep Stages Clear\nDefine **3–7 stages** with objective entry criteria. Avoid vague stages like "In Progress".\n\n### Enforce Data Hygiene\n- Set mandatory fields for each stage transition.\n- Archive stale deals older than 90 days.\n\n### Review Weekly\nHold a 30-minute pipeline review each week:\n1. Identify deals that have not advanced in 14+ days.\n2. Validate close dates and amounts.\n3. Flag at-risk deals for coaching.\n\n### Leverage AI Insights\nEnable Predictive Deal Scoring to automatically surface deals most likely to close.', category: 'best_practices', status: 'published', is_featured: true, view_count: 3640, helpful_count: 312 },
  { title: 'How to Create Custom Reports', summary: 'Step-by-step instructions for building, filtering, and scheduling custom reports.', body: '## How to Create Custom Reports\n\n1. Navigate to **Reports → New Report**.\n2. Select a report type (Tabular, Summary, or Matrix).\n3. Choose the primary object (e.g., Opportunities).\n4. Add columns by dragging fields from the field palette.\n5. Apply filters to narrow results (e.g., `close_date >= THIS_QUARTER`).\n6. Click **Run** to preview.\n7. Save and optionally schedule delivery via email.\n\n### Tips\n- Use **cross-filters** to find records with or without related records.\n- Group by `stage` or `owner` for summary insights.\n- Export to CSV or PDF from the report toolbar.', category: 'how_to', status: 'published', is_featured: false, view_count: 2980, helpful_count: 245 },
  { title: 'Frequently Asked Questions', summary: 'Answers to the most common questions about billing, data limits, and integrations.', body: '## Frequently Asked Questions\n\n### How many users can I add?\nUser limits depend on your plan: Starter (5), Professional (unlimited), Enterprise (unlimited).\n\n### Can I import data from Salesforce?\nYes. Use the Salesforce Connector add-on for bidirectional sync, or do a one-time CSV export/import.\n\n### What is the API rate limit?\nThe default rate limit is 10,000 requests per hour per organization. Contact support to request an increase.\n\n### How do I upgrade my plan?\nGo to **Settings → Billing → Change Plan** and select your new tier. Changes take effect immediately.\n\n### Is my data encrypted?\nAll data is encrypted at rest (AES-256) and in transit (TLS 1.3).', category: 'faq', status: 'draft', is_featured: false, view_count: 1520, helpful_count: 134 },
];

export default KbArticleSeedData;
